import argparse
import csv
import re
import typing as t
from pathlib import Path

import anndata
import pandas as pd

ORGAN_LEVEL = "anatomogram"
LABEL_COLUMN = "authors_cell_type_-_ontology_labels"
IRI_COLUMN = "authors_cell_type_-_ontology_labels_ontology"
CL_IRI_PATTERN = re.compile(r"^http://purl\.obolibrary\.org/obo/(P?CL)_(\d+)$")

# Must match the organs in utils.js
EXPERIMENT_ORGANS = {
    "E-CURD-119": "UBERON:0002113",
    "E-MTAB-10553": "UBERON:0002107",
    "E-GEOD-130148": "UBERON:0002048",
    "E-MTAB-5061": "UBERON:0001264",
}

HEADER_ROWS = [
    ["Crosswalk of author assigned cell types to Cell Ontology", "", "", "", "", "", ""],
    ["", "", "", "", "", "", ""],
    ["Source:", "Author assigned cell types from datasets with Cell Ontology mappings", "", "", "", "", ""],
    [f"Organ Level {ORGAN_LEVEL}:", "EBI Single Cell Expression Atlas (https://www.ebi.ac.uk/gxa/sc/)", "", "", "", "", ""],
    ["Generated by:", "src/anatomogram/build_crosswalk.py", "", "", "", "", ""],
    ["", "", "", "", "", "", ""],
]
COLUMNS = ["Organ_Level", "Organ_ID", "Annotation_Label", "Annotation_Label_ID", "CL_Label", "CL_ID", "CL_Match"]


def get_rows(file: Path, organ: str) -> t.List[t.Dict[str, str]]:
    obs = anndata.read_h5ad(file, backed="r").obs[[LABEL_COLUMN, IRI_COLUMN]].dropna()
    obs = obs.astype(str)
    counts = obs.groupby([LABEL_COLUMN, IRI_COLUMN]).size().reset_index(name="count")
    # Use the most common ontology term if a label maps to multiple terms
    counts = counts.sort_values("count", ascending=False).drop_duplicates(LABEL_COLUMN)

    rows = []
    for label, iri in zip(counts[LABEL_COLUMN], counts[IRI_COLUMN]):
        match = CL_IRI_PATTERN.match(iri.strip())
        if not match or label.strip().lower() in ("", "nan"):
            continue
        rows.append(
            {
                "Organ_Level": ORGAN_LEVEL,
                "Organ_ID": organ,
                "Annotation_Label": label.strip(),
                "CL_Label": label.strip(),
                "CL_ID": f"{match[1]}:{match[2]}",
                "CL_Match": "skos:exactMatch",
            }
        )
    return sorted(rows, key=lambda row: row["Annotation_Label"].lower())


def main(args: argparse.Namespace):
    rows = []
    for code, organ in EXPERIMENT_ORGANS.items():
        file = args.cache_dir / f"{code}.project.h5ad"
        if not file.exists():
            raise FileNotFoundError(f"Missing experiment file {file}")
        rows.extend(get_rows(file, organ))

    # Deduplicate rows for experiments sharing an organ
    rows = list({(row["Organ_ID"], row["Annotation_Label"]): row for row in rows}.values())
    for index, row in enumerate(rows, 1):
        row["Annotation_Label_ID"] = f"AUTH:{index:07d}"

    with open(args.output, "w", newline="") as file:
        writer = csv.writer(file)
        writer.writerows(HEADER_ROWS)
        dict_writer = csv.DictWriter(file, fieldnames=COLUMNS)
        dict_writer.writeheader()
        dict_writer.writerows(rows)


def _get_arg_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Build the author crosswalk table for anatomogram datasets")
    parser.add_argument(
        "--cache-dir", type=Path, default=Path("tmp/anatomogram"), help="Directory with the cached experiment h5ad files"
    )
    parser.add_argument("--output", type=Path, default=Path("crosswalking-tables/author.csv"), help="Output csv file")
    return parser


if __name__ == "__main__":
    parser = _get_arg_parser()
    args = parser.parse_args()
    main(args)
